### ISSUE TITLE
Update to JupyterLab 4

### ISSUE THREAD

**Issue by jtpio** [jupyterlab-contrib/jupyterlab-cell-flash#41]
## Is your feature request related to a problem? Please describe.

The extension is built for JupyterLab 3 for now.

## Describe the solution you'd like

JupyterLab 4 support.

Probably not much to be done. Maybe updating to the latest extension template would be useful to grab all the latest changes: https://github.com/jupyterlab/extension-template

## Additional context

This would be useful for JupyterLite 0.2.0: https://github.com/jupyterlite/jupyterlite/releases/tag/v0.2.0a0

**Comment by mengyanw** [comment]
Hi @jtpio, I've raised a PR #43
